### ISSUE TITLE
was this even obf in the first place?

### ISSUE THREAD

**Issue by Z3R0-cmd** [YeahOMA/hawk-client#3]
btw jcolor is directly pasted from a anarchy client

**Comment by quickdaffy** [comment]
ok mr i left the community!!1111

**Comment by pofouMc** [comment]
yes

**Comment by pofouMc** [comment]
> ok mr i left the community!!1111

omg its skidd

**Comment by Z3R0-cmd** [comment]
community != github 
nerd

**Comment by quickdaffy** [comment]
seems you are on a github page that ahs to do with the community, and you're interacting with people in the community. go write another blink.

**Comment by Z3R0-cmd** [comment]
does nobody understand what a joke is these days? also I'm assuming you have some 'hawk client' or 'garbage client' of your own that is copy pasting? at this point I don't care. continue skidding and have fun annoying the heck out of real developers.

**Comment by quickdaffy** [comment]
yes i skidded your blink- i mean redesky disabler!
